UPDATE: better onedrive-sync script

diff --git a/onedrive-sync b/onedrive-sync
--- a/onedrive-sync
+++ b/onedrive-sync
@@ -1,6 +1,22 @@
 #!/bin/bash
 
-# syncs onedrive (used in crontab)
-echo "$(date '+%d-%m-%Y %H:%M:%S') zenbook: (m1tus) CMD(onedrive --synchronize)" >> /var/log/m1tus-scripts.log
-onedrive --synchronize 2>>/var/log/m1tus-scripts.log
+LOGFILE="/home/m1tus/.log/onedrive-sync.log"
+LOGDIR=$(dirname $LOGFILE)
 
+# Check for .log dir
+if [ ! -d $LOGDIR ]; then
+    echo "Dir $LOGDIR does not exist"
+    exit 1
+fi
+
+# Try to create LOGFILE
+touch $LOGFILE
+
+if [ $? -ne 0 ]; then
+    echo "Log file could not be created. Check permissions"
+    exit 1
+fi
+
+# syncs onedrive (used in crontab)
+echo "$(date '+%d-%m-%Y %H:%M:%S') zenbook: (m1tus) CMD(onedrive --synchronize)" >> $LOGFILE
+onedrive --synchronize 2>> $LOGFILE
